/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tampilan;

import java.sql.*;
import koneksi.koneksi;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import login.login;

/**
 *
 * @author Asus
 */
public class datakriteria extends javax.swing.JFrame {

    public datakriteria() {
        initComponents();
        this.setLocationRelativeTo(null);
        showTableKriteria();
        showTableSubKriteria();
        addTableListeners();
    }

    Connection conn = new koneksi().connect();
    private DefaultTableModel modelKriteria;
    private DefaultTableModel modelSubKriteria;

    private void cekKosongKriteria() throws exceptionData {
        if (tfnamaKriteria.getText().isEmpty()
                || tfbobotKriteria.getText().isEmpty()
                || cbatributKriteria.getSelectedItem().toString().isEmpty()) {
            throw new exceptionData();
        }
    }

    private void cekKosongSubKriteria() throws exceptionData {
        if (tfIdSubKriteria.getText().trim().isEmpty()
                || tfnamaSubKriteria.getText().trim().isEmpty()
                || tfbobotSubKriteria.getText().trim().isEmpty()
                || cbKdSubKriteria.getSelectedItem() == null) {

            throw new exceptionData("Silahkan isi data dengan lengkap!");
        }
    }

    private void addTableListeners() {
        TableKriteria.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                int row = TableKriteria.getSelectedRow();
                if (row != -1) {
                    tfKdKriteria.setText(TableKriteria.getValueAt(row, 1).toString());
                    tfnamaKriteria.setText(TableKriteria.getValueAt(row, 2).toString());
                    tfbobotKriteria.setText(TableKriteria.getValueAt(row, 3).toString());
                    cbatributKriteria.setSelectedItem(TableKriteria.getValueAt(row, 4).toString());
                }
            }
        });

        TableSubKriteria.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                int row = TableSubKriteria.getSelectedRow();
                if (row != -1) {
                    tfIdSubKriteria.setText(TableSubKriteria.getValueAt(row, 1).toString());
                    cbKdSubKriteria.setSelectedItem(TableSubKriteria.getValueAt(row, 2).toString());
                    tfnamaSubKriteria.setText(TableSubKriteria.getValueAt(row, 3).toString());
                    tfbobotSubKriteria.setText(TableSubKriteria.getValueAt(row, 4).toString());
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jpFrame = new javax.swing.JPanel();
        jpAtas = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jpKiri = new javax.swing.JPanel();
        jbHome = new javax.swing.JButton();
        jbDataSiswa = new javax.swing.JButton();
        jbDataKriteria = new javax.swing.JButton();
        jbDataPen = new javax.swing.JButton();
        jbDataPer = new javax.swing.JButton();
        jbLogout = new javax.swing.JButton();
        jbLaporan = new javax.swing.JButton();
        jpKanan = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableKriteria = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        TableSubKriteria = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tfKdKriteria = new javax.swing.JTextField();
        tfnamaKriteria = new javax.swing.JTextField();
        tfbobotKriteria = new javax.swing.JTextField();
        cbatributKriteria = new javax.swing.JComboBox<>();
        btnEditKriteria = new javax.swing.JButton();
        btnResetKriteria = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        tfIdSubKriteria = new javax.swing.JTextField();
        tfnamaSubKriteria = new javax.swing.JTextField();
        tfbobotSubKriteria = new javax.swing.JTextField();
        btnEditSub = new javax.swing.JButton();
        btnHapusSub = new javax.swing.JButton();
        btnResetSub = new javax.swing.JButton();
        cbKdSubKriteria = new javax.swing.JComboBox<>();
        btnTambahSub = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        tfCariKriteria = new javax.swing.JTextField();
        btnCariKriteria = new javax.swing.JButton();
        btnCariSubKriteria = new javax.swing.JButton();
        btsRefreshSubKriteria = new javax.swing.JButton();
        btnRefreshKriteria = new javax.swing.JButton();
        tfCariSubKriteria = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(1000, 650));

        jpFrame.setBackground(new java.awt.Color(0, 102, 102));
        jpFrame.setPreferredSize(new java.awt.Dimension(1000, 650));

        jpAtas.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("MI Nurul Huda");

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/WhatsApp Image 2025-07-20 at 21.22.03.jpeg"))); // NOI18N

        javax.swing.GroupLayout jpAtasLayout = new javax.swing.GroupLayout(jpAtas);
        jpAtas.setLayout(jpAtasLayout);
        jpAtasLayout.setHorizontalGroup(
            jpAtasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpAtasLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel14)
                .addGap(60, 60, 60)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpAtasLayout.setVerticalGroup(
            jpAtasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpAtasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpAtasLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel14)
                .addGap(15, 15, 15))
        );

        jpKiri.setBackground(new java.awt.Color(0, 153, 153));
        jpKiri.setPreferredSize(new java.awt.Dimension(100, 400));

        jbHome.setText("Home");
        jbHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbHomeActionPerformed(evt);
            }
        });

        jbDataSiswa.setText("Data Siswa");
        jbDataSiswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbDataSiswaActionPerformed(evt);
            }
        });

        jbDataKriteria.setText("Data Kriteria");
        jbDataKriteria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbDataKriteriaActionPerformed(evt);
            }
        });

        jbDataPen.setText("Data Penilaian");
        jbDataPen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbDataPenActionPerformed(evt);
            }
        });

        jbDataPer.setText("Data Perhitungan");
        jbDataPer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbDataPerActionPerformed(evt);
            }
        });

        jbLogout.setText("Logout");
        jbLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLogoutActionPerformed(evt);
            }
        });

        jbLaporan.setText("Laporan");
        jbLaporan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLaporanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpKiriLayout = new javax.swing.GroupLayout(jpKiri);
        jpKiri.setLayout(jpKiriLayout);
        jpKiriLayout.setHorizontalGroup(
            jpKiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpKiriLayout.createSequentialGroup()
                .addGroup(jpKiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpKiriLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jpKiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbDataSiswa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbDataKriteria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbDataPen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jpKiriLayout.createSequentialGroup()
                                .addComponent(jbDataPer)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jpKiriLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jbLogout)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jpKiriLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jbLaporan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jpKiriLayout.setVerticalGroup(
            jpKiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpKiriLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jbHome)
                .addGap(18, 18, 18)
                .addComponent(jbDataSiswa)
                .addGap(18, 18, 18)
                .addComponent(jbDataKriteria)
                .addGap(18, 18, 18)
                .addComponent(jbDataPen)
                .addGap(18, 18, 18)
                .addComponent(jbDataPer)
                .addGap(18, 18, 18)
                .addComponent(jbLaporan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 135, Short.MAX_VALUE)
                .addComponent(jbLogout)
                .addGap(16, 16, 16))
        );

        jpKanan.setBackground(new java.awt.Color(0, 204, 204));
        jpKanan.setPreferredSize(new java.awt.Dimension(600, 390));

        jPanel5.setBackground(new java.awt.Color(0, 204, 204));
        jPanel5.setMinimumSize(new java.awt.Dimension(100, 100));
        jPanel5.setPreferredSize(new java.awt.Dimension(837, 518));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel15.setText("~ Data Kriteria ~");

        TableKriteria.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        jScrollPane1.setViewportView(TableKriteria);

        TableSubKriteria.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        jScrollPane2.setViewportView(TableSubKriteria);

        jPanel6.setBackground(new java.awt.Color(0, 204, 204));
        jPanel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(0, 0, 0), null, null));

        jLabel2.setText("Kode Kriteria");

        jLabel3.setText("Nama Kriteria");

        jLabel4.setText("Bobot Kriteria");

        jLabel5.setText("Atribut");

        cbatributKriteria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Benefit", "Cost" }));

        btnEditKriteria.setText("Edit");
        btnEditKriteria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditKriteriaActionPerformed(evt);
            }
        });

        btnResetKriteria.setText("Reset");
        btnResetKriteria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetKriteriaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbatributKriteria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfKdKriteria, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfnamaKriteria, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfbobotKriteria, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(btnEditKriteria)
                        .addGap(66, 66, 66)
                        .addComponent(btnResetKriteria)))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(tfKdKriteria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tfnamaKriteria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(tfbobotKriteria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(125, 125, 125))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(cbatributKriteria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnEditKriteria)
                            .addComponent(btnResetKriteria))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        jPanel2.setBackground(new java.awt.Color(0, 204, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(0, 0, 0), null, null));

        jLabel6.setText("Kode Kriteria");

        jLabel7.setText("ID SubKriteria");

        jLabel8.setText("Nama SubKriteria");

        jLabel9.setText("Bobot SubKriteria");

        btnEditSub.setText("Edit");
        btnEditSub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditSubActionPerformed(evt);
            }
        });

        btnHapusSub.setText("Hapus");
        btnHapusSub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusSubActionPerformed(evt);
            }
        });

        btnResetSub.setText("Reset");
        btnResetSub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetSubActionPerformed(evt);
            }
        });

        cbKdSubKriteria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "C1", "C2", "C3", "C4", "C5" }));

        btnTambahSub.setText("Tambah");
        btnTambahSub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahSubActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnTambahSub)
                        .addGap(18, 18, 18)
                        .addComponent(btnEditSub, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnHapusSub, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnResetSub, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7))
                                .addGap(39, 39, 39)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfIdSubKriteria, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbKdSubKriteria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel9)
                                    .addGap(18, 18, 18)
                                    .addComponent(tfbobotSubKriteria))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel8)
                                    .addGap(18, 18, 18)
                                    .addComponent(tfnamaSubKriteria, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(46, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cbKdSubKriteria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfIdSubKriteria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(tfnamaSubKriteria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(tfbobotSubKriteria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEditSub)
                    .addComponent(btnHapusSub)
                    .addComponent(btnResetSub)
                    .addComponent(btnTambahSub))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setText("Tabel Kriteria");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setText("Tabel SubKriteria");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setText("Cari Data:");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel13.setText("Cari Data:");

        btnCariKriteria.setText("Cari");
        btnCariKriteria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariKriteriaActionPerformed(evt);
            }
        });

        btnCariSubKriteria.setText("Cari");
        btnCariSubKriteria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariSubKriteriaActionPerformed(evt);
            }
        });

        btsRefreshSubKriteria.setText("Refresh");
        btsRefreshSubKriteria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btsRefreshSubKriteriaActionPerformed(evt);
            }
        });

        btnRefreshKriteria.setText("Refresh");
        btnRefreshKriteria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshKriteriaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(348, 348, 348)
                        .addComponent(jLabel13))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(333, 333, 333)
                        .addComponent(jLabel15))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel5Layout.createSequentialGroup()
                                    .addComponent(tfCariKriteria, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnCariKriteria)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnRefreshKriteria))
                                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addGap(26, 26, 26)
                                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel11)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tfCariSubKriteria, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnCariSubKriteria)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btsRefreshSubKriteria)))
                                .addGap(2, 2, 2)))))
                .addGap(0, 19, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel15)
                .addGap(10, 10, 10)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(btnRefreshKriteria)
                    .addComponent(btnCariKriteria)
                    .addComponent(tfCariKriteria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(btsRefreshSubKriteria)
                    .addComponent(btnCariSubKriteria)
                    .addComponent(tfCariSubKriteria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE))
                .addGap(34, 34, 34))
        );

        javax.swing.GroupLayout jpKananLayout = new javax.swing.GroupLayout(jpKanan);
        jpKanan.setLayout(jpKananLayout);
        jpKananLayout.setHorizontalGroup(
            jpKananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 837, Short.MAX_VALUE)
            .addGroup(jpKananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jpKananLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jpKananLayout.setVerticalGroup(
            jpKananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 518, Short.MAX_VALUE)
            .addGroup(jpKananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jpKananLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jpFrameLayout = new javax.swing.GroupLayout(jpFrame);
        jpFrame.setLayout(jpFrameLayout);
        jpFrameLayout.setHorizontalGroup(
            jpFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jpFrameLayout.createSequentialGroup()
                        .addComponent(jpKiri, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jpKanan, javax.swing.GroupLayout.PREFERRED_SIZE, 837, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jpAtas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpFrameLayout.setVerticalGroup(
            jpFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpFrameLayout.createSequentialGroup()
                .addComponent(jpAtas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addGroup(jpFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jpKiri, javax.swing.GroupLayout.DEFAULT_SIZE, 518, Short.MAX_VALUE)
                    .addComponent(jpKanan, javax.swing.GroupLayout.DEFAULT_SIZE, 518, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jpFrame, javax.swing.GroupLayout.PREFERRED_SIZE, 985, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jpFrame, javax.swing.GroupLayout.PREFERRED_SIZE, 613, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 985, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 613, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbHomeActionPerformed
        // TODO add your handling code here:
        new menu().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbHomeActionPerformed

    private void jbDataSiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbDataSiswaActionPerformed
        // TODO add your handling code here:
        new datasiswa().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbDataSiswaActionPerformed

    private void jbDataKriteriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbDataKriteriaActionPerformed
        // TODO add your handling code here:
        new datakriteria().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbDataKriteriaActionPerformed

    private void jbDataPenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbDataPenActionPerformed
        // TODO add your handling code here:
        new datapenilaian().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbDataPenActionPerformed

    private void jbDataPerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbDataPerActionPerformed
        // TODO add your handling code here:
        new dataperhitungan().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbDataPerActionPerformed

    private void jbLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLogoutActionPerformed
        // TODO add your handling code here:
        int response = JOptionPane.showConfirmDialog(
                this,
                "Apakah Anda yakin ingin Logout?",
                "Konfirmasi Keluar",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE);
        if (response == JOptionPane.YES_OPTION) {
            login login = new login();
            login.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_jbLogoutActionPerformed

    private void jbLaporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLaporanActionPerformed
        // TODO add your handling code here:
        new laporan().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbLaporanActionPerformed

    private void btnEditKriteriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditKriteriaActionPerformed
        // TODO add your handling code here:
        try {
            cekKosongKriteria();
        } catch (exceptionData ex) {
            JOptionPane.showMessageDialog(null, ex.showMessageError());
        }
        editKriteria();
        resetKriteria();
    }//GEN-LAST:event_btnEditKriteriaActionPerformed

    public void editKriteria() {
        try {
            String query;
            query = "UPDATE kriteria SET nama_kriteria=?, bobot_kriteria=?, atribut=? WHERE kode_kriteria=?";
            PreparedStatement st = conn.prepareStatement(query);
            st.setString(1, tfnamaKriteria.getText());
            st.setString(2, tfbobotKriteria.getText());
            st.setString(3, cbatributKriteria.getSelectedItem().toString());
            st.setString(4, tfKdKriteria.getText());
            st.executeUpdate();
            tfKdKriteria.requestFocus();
            JOptionPane.showMessageDialog(null, "data berhasil diedit");
            showTableKriteria();
        } catch (SQLException ex) {
            Logger.getLogger(datakriteria.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "data gagal diedit" + ex.getMessage());
        }
    }

    private void btnResetKriteriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetKriteriaActionPerformed
        // TODO add your handling code here:
        resetKriteria();
    }//GEN-LAST:event_btnResetKriteriaActionPerformed

    private void btnEditSubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditSubActionPerformed
        // TODO add your handling code here:
        try {
            cekKosongKriteria();
        } catch (exceptionData ex) {
            JOptionPane.showMessageDialog(null, ex.showMessageError());
        }
        editSubKriteria();
        resetSubKriteria();
    }//GEN-LAST:event_btnEditSubActionPerformed

    private void btnHapusSubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusSubActionPerformed
        // TODO add your handling code here:
        hapusSubKriteria();
        resetSubKriteria();
    }//GEN-LAST:event_btnHapusSubActionPerformed

    private void btnResetSubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetSubActionPerformed
        // TODO add your handling code here:
        resetSubKriteria();
    }//GEN-LAST:event_btnResetSubActionPerformed

    private void btnTambahSubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahSubActionPerformed
        // TODO add your handling code here:
        try {
            cekKosongSubKriteria();
        } catch (exceptionData ex) {
            JOptionPane.showMessageDialog(null, ex.showMessageError());
        }
        tambahSubKriteria();
        resetSubKriteria();
    }//GEN-LAST:event_btnTambahSubActionPerformed

    public void resetKriteria() {
        tfKdKriteria.setText("");
        tfnamaKriteria.setText("");
        tfbobotKriteria.setText("");
        cbatributKriteria.setSelectedIndex(0);
    }

    protected void showTableKriteria() {
        Object[] baris = {"No", "Kode Kriteria", "Nama Kriteria", "Bobot Kriteria", "Atribut Kriteria"};
        modelKriteria = new DefaultTableModel(null, baris);
        TableKriteria.setModel(modelKriteria);
        String query;
        query = "SELECT * FROM kriteria ORDER by kode_kriteria";
        try {
            java.sql.Statement st = conn.createStatement();
            ResultSet hasil = st.executeQuery(query);
            int no = 1;
            while (hasil.next()) {
                String a = String.valueOf(no);
                String b = hasil.getString("kode_kriteria");
                String c = hasil.getString("nama_kriteria");
                String d = hasil.getString("bobot_kriteria");
                String e = hasil.getString("atribut");
                String[] data = {a, b, c, d, e};
                modelKriteria.addRow(data);
                no++;
            }
        } catch (SQLException e) {
            Logger.getLogger(datakriteria.class.getName()).log(Level.SEVERE, null, e);
        }
    }

    public void editSubKriteria() {
        try {
            try {
                cekKosongSubKriteria();
            } catch (exceptionData ex) {
                JOptionPane.showMessageDialog(null, ex.showMessageError());
                return;
            }

            String query = "UPDATE subkriteria SET nama_subkriteria=?, bobot_subkriteria=?, kode_kriteria=? WHERE id_subkriteria=?";
            PreparedStatement st = conn.prepareStatement(query);

            String namaSub = tfnamaSubKriteria.getText();
            String bobotStr = tfbobotSubKriteria.getText().replace("Rp.", "").replace(".", "").replace(",", ".").replace(">", "").replace("<", "").trim();

            double bobot;
            try {
                bobot = Double.parseDouble(bobotStr);
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Format bobot tidak valid. Harus berupa angka (misal: 2.5)");
                return;
            }

            st.setString(1, namaSub);
            st.setDouble(2, bobot);
            st.setString(3, cbKdSubKriteria.getSelectedItem().toString());
            st.setString(4, tfIdSubKriteria.getText());

            st.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data berhasil diedit");

            showTableSubKriteria();

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Data gagal diedit: " + ex.getMessage());
            Logger.getLogger(datakriteria.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void hapusSubKriteria() {
        try {
            String query;
            query = "DELETE FROM subkriteria where id_subkriteria = ? ";
            PreparedStatement st = conn.prepareStatement(query);
            st.setString(1, tfIdSubKriteria.getText());
            JOptionPane.showMessageDialog(null, "data berhasil dihapus");
            st.executeUpdate();
            tfIdSubKriteria.requestFocus();
            showTableKriteria();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "data gagal dihapus " + ex.getMessage());
        }
        showTableSubKriteria();
    }

    public void tambahSubKriteria() {
        String query;
        query = "INSERT INTO subkriteria " + "(id_subkriteria,kode_kriteria,nama_subkriteria,bobot_subkriteria)" + "VALUES (?,?,?,?)";
        PreparedStatement statement;
        Connection connect;
        try {
            Connection conn = new koneksi().connect();
            statement = conn.prepareStatement(query);
            statement.setString(1, tfIdSubKriteria.getText());
            statement.setString(2, cbKdSubKriteria.getSelectedItem().toString());
            statement.setString(3, tfnamaSubKriteria.getText());
            statement.setString(4, tfbobotSubKriteria.getText());
            int cek = statement.executeUpdate();
            if (cek == 1) {
                JOptionPane.showMessageDialog(null, "data berhasil ditambahkan");
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "gagal menambahkan data " + e.getMessage());
        }
        showTableSubKriteria();
    }

    public void resetSubKriteria() {
        tfnamaSubKriteria.setText("");
        tfbobotSubKriteria.setText("");
        cbKdSubKriteria.setSelectedIndex(0);
        tfIdSubKriteria.setText("");
    }

    protected void showTableSubKriteria() {
        Object[] baris = {"No", "Id SubKriteria", "Kode Kriteria", "Nama SubKriteria", "Bobot SubKriteria"};
        modelSubKriteria = new DefaultTableModel(null, baris);
        TableSubKriteria.setModel(modelSubKriteria);
        String query;
        query = "SELECT * FROM subkriteria ORDER BY kode_kriteria";
        try {
            java.sql.Statement st = conn.createStatement();
            ResultSet hasil = st.executeQuery(query);
            int no = 1;
            while (hasil.next()) {
                String a = String.valueOf(no);
                String b = hasil.getString("id_subkriteria");
                String c = hasil.getString("kode_kriteria");
                String d = hasil.getString("nama_subkriteria");
                String e = hasil.getString("bobot_subkriteria");
                String[] data = {a, b, c, d, e};
                modelSubKriteria.addRow(data);
                no++;
            }
        } catch (SQLException e) {
            Logger.getLogger(datakriteria.class.getName()).log(Level.SEVERE, null, e);
        }
    }

    private void btnCariKriteriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariKriteriaActionPerformed
        Object[] baris = {"No", "Kode Kriteria", "Nama Kriteria", "Bobot Kriteria", "Atribut Kriteria"};
        modelKriteria = new DefaultTableModel(null, baris);
        TableKriteria.setModel(modelKriteria);
        String query = "SELECT * FROM kriteria WHERE kode_kriteria LIKE ? OR nama_kriteria LIKE ?";
        try {
            PreparedStatement st = conn.prepareStatement(query);
            String keyword = "%" + tfCariKriteria.getText() + "%";
            st.setString(1, keyword);
            st.setString(2, keyword);
            ResultSet hasil = st.executeQuery();
            int no = 1;
            while (hasil.next()) {
                String[] data = {
                    String.valueOf(no++),
                    hasil.getString("kode_kriteria"),
                    hasil.getString("nama_kriteria"),
                    hasil.getString("bobot_kriteria"),
                    hasil.getString("atribut")
                };
                modelKriteria.addRow(data);
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
        tfCariKriteria.setText("");
    }//GEN-LAST:event_btnCariKriteriaActionPerformed

    private void btnCariSubKriteriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariSubKriteriaActionPerformed
        // TODO add your handling code here:
        Object[] baris = {"No", "ID SubKriteria", "Kode Kriteria", "Nama SubKriteria", "Bobot SubKriteria"};
        modelSubKriteria = new DefaultTableModel(null, baris);
        TableSubKriteria.setModel(modelSubKriteria);
        String query;
        query = "SELECT * FROM subkriteria where kode_kriteria LIKE " + "'%" + tfCariSubKriteria.getText() + "%' OR nama_subkriteria LIKE " + "'%" + tfCariSubKriteria.getText() + "%'";
        try {
            java.sql.Statement st = conn.createStatement();
            ResultSet hasil = st.executeQuery(query);
            int no = 1;
            while (hasil.next()) {
                String a = String.valueOf(no);
                String b = hasil.getString("id_subkriteria");
                String c = hasil.getString("kode_kriteria");
                String d = hasil.getString("nama_subkriteria");
                String e = hasil.getString("bobot_subkriteria");
                String[] data = {a, b, c, d, e};
                modelSubKriteria.addRow(data);
                no++;
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
        tfCariSubKriteria.setText("");
    }//GEN-LAST:event_btnCariSubKriteriaActionPerformed

    private void btsRefreshSubKriteriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btsRefreshSubKriteriaActionPerformed
        // TODO add your handling code here:
        showTableSubKriteria();
        tfCariSubKriteria.setText("");
    }//GEN-LAST:event_btsRefreshSubKriteriaActionPerformed

    private void btnRefreshKriteriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshKriteriaActionPerformed
        // TODO add your handling code here:
        showTableKriteria();
        tfCariKriteria.setText("");
    }//GEN-LAST:event_btnRefreshKriteriaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(datakriteria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(datakriteria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(datakriteria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(datakriteria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new datakriteria().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TableKriteria;
    private javax.swing.JTable TableSubKriteria;
    private javax.swing.JButton btnCariKriteria;
    private javax.swing.JButton btnCariSubKriteria;
    private javax.swing.JButton btnEditKriteria;
    private javax.swing.JButton btnEditSub;
    private javax.swing.JButton btnHapusSub;
    private javax.swing.JButton btnRefreshKriteria;
    private javax.swing.JButton btnResetKriteria;
    private javax.swing.JButton btnResetSub;
    private javax.swing.JButton btnTambahSub;
    private javax.swing.JButton btsRefreshSubKriteria;
    private javax.swing.JComboBox<String> cbKdSubKriteria;
    private javax.swing.JComboBox<String> cbatributKriteria;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jbDataKriteria;
    private javax.swing.JButton jbDataPen;
    private javax.swing.JButton jbDataPer;
    private javax.swing.JButton jbDataSiswa;
    private javax.swing.JButton jbHome;
    private javax.swing.JButton jbLaporan;
    private javax.swing.JButton jbLogout;
    private javax.swing.JPanel jpAtas;
    private javax.swing.JPanel jpFrame;
    private javax.swing.JPanel jpKanan;
    private javax.swing.JPanel jpKiri;
    private javax.swing.JTextField tfCariKriteria;
    private javax.swing.JTextField tfCariSubKriteria;
    private javax.swing.JTextField tfIdSubKriteria;
    private javax.swing.JTextField tfKdKriteria;
    private javax.swing.JTextField tfbobotKriteria;
    private javax.swing.JTextField tfbobotSubKriteria;
    private javax.swing.JTextField tfnamaKriteria;
    private javax.swing.JTextField tfnamaSubKriteria;
    // End of variables declaration//GEN-END:variables
}
